# Configuration file example

model:
  name: ResNet
  num_layers: 18
  dropout: 0.2

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 10

data:
  dataset: MNIST
  data_dir: ../../data/MNIST/
  train_split: 0.8
  random_seed: 123

logging:
  log_dir: logs
  log_level: INFO

results:
  results_dir: ../../results/